name: nirvana
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    platform: linux/arm64/v8
    volumes:
      - .:/app

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    platform: linux/arm64/v8
    volumes:
      - .:/app
    depends_on:
      - flask-app
