name: nirvana
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    platform: linux/amd64
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app