FROM tensorflow/tensorflow

WORKDIR /app
COPY . /app

RUN pip install --ignore-installed blinker 
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8501

CMD ["streamlit", "run", "Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
