FROM tensorflow/tensorflow

WORKDIR /app
COPY . /app

RUN pip install --ignore-installed blinker 
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]
